### ISSUE TITLE
bug when new articles

### ISSUE THREAD

**Issue by web54** [FLEXIcontent/flexicontent-cck#1188]
new joomla 4.4.2 
flexicontent master : 4.2.1   Release date: 2023-07-15

new article saved : 
message : 
Assigned item to Default Workflow
Item saved
category view screenshot : 
![image](https://github.com/FLEXIcontent/flexicontent-cck/assets/9278935/d796fa90-74ba-43e4-9443-112849e7a99e)
to enable the article I have to click on the button AND refresh catégory view page

Got the same issue with that flexicontent on the same server ( 3 sites ( 2 existing were working well before update to this master)

**Comment by micker** [comment]
You use joomla form or flexicontent
That do same thing in all types ?
Thanks for return

**Comment by web54** [comment]
flexi form
in all types ? As I wrote, event in a fresh site

**Comment by micker** [comment]
As i see in article
But if you creat a type ?

**Comment by web54** [comment]
testé sur un autre type, puis sur nouveau type, et ça buggue toujours

**Comment by micker** [comment]
hello i do test on your site and in fresh site 
its not a bug :
1 message about workflow is only display because your are in debug mode
2 the state is normal because you have 1h of difference between your server and your site confguration
![image](https://github.com/FLEXIcontent/flexicontent-cck/assets/2539440/f23c25df-3516-471f-8671-4b50bad0b7c8)
when you create an item it add a date without hours maybe a mistake in your configuration
