### ISSUE TITLE
Readon SPAN block should be in template file instead of being inside mod_flexicontent.php 

### ISSUE THREAD

**Issue by Igcorreia** [FLEXIcontent/flexicontent-cck#173]
I need to customize the span that allows on the module to link to a desired page:

line: 213 -> modules/mod_flexicontent/mod_flexicontent.php
```
	// Add module Read More
	if ($show_more == 1) : ?>
	<span class="module_readon<?php echo $params->get('moduleclass_sfx'); ?>"<?php if ($more_css) : ?> style="<?php echo $more_css; ?>"<?php endif;?>>
		<a class="readon" href="<?php echo JRoute::_($more_link); ?>" <?php if ($params->get('more_blank') == 1) {echo 'target="_blank"';} ?>><span><?php echo JText::_($more_title); ?></span></a>
	</span>
	<?php endif;>
```

This should be moved to each template so it can be customized. 
No design elements should be on the mod_flexicontent.php

**Comment by ggppdk** [comment]
+ 2 improvements,

1st, allowed CSS to be placed by FLEXIcontent modules, thus extensions that capture module's HTML will have work easier work,

2nd added Joomla template overridable header.php and footer.php in each template folder of the universal content module, these files can be copied to the Joomla template to customize

if you wonder why we do not place header and footer inside the main layout file, the answer is because the layout file will be loaded multiple times when you enable parameter:
"Apply configuration per category"

Also inside the module there are now 2 readme files that say 
- how to create a new template 
- how to use a Joomla template override
