### ISSUE TITLE
Univ. Content Module for FLEXIcontent $catdata undefined

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#177]
Hello,

I'm using the latest build beta 6 nightly 3, $catdata is undefined in tmpl_common/category.php

Thanks.

**Comment by ggppdk** [comment]
Parameter apply data per category is On?  Or off?

**Comment by ldoliv** [comment]
Hello,
The parameter "Apply configuration per category" is disabled. I'm using a template in the module folder not in the template overrides.

I'm guessing it's related to the nonumber adv. module manager.

I've stripped everything from the template except for a simple <div>test</div>, and I'm guetting inside my module code as if 3 modules.
            
<div class="default mod_flexicontent_wrapper mod_flexicontent_wrapheadimg" id="mod_flexicontent_default136">
                Notice: Undefined variable: catdata in /home/vhosts/blizzardlighting.com/httpdocs/modules/mod_flexicontent/tmpl_common/category.php on line 1
            </div>
            <div>test</div>
            <div class="default mod_flexicontent_wrapper mod_flexicontent_wrapheadimg" id="mod_flexicontent_default136">
                <div id="order_added136" class="mod_flexicontent">
                
                <ul class="mod_flexicontentheadimg mod_flexicontent_standard">
                    <li class="fcitem_active">
                    <a href="/contact-us">Contact Us</a>
                    </li>
                    
                </ul>
                
            </div>

**Comment by ggppdk** [comment]
Please test with built-in templates without changes, does it work in this case ?

**Comment by ldoliv** [comment]
Yes, it works with the build in templates, but if I duplicate say the news.php and news.xml to mynews.php and mynews.xml the same problem occurs, in the module it has 3 div containers.

**Comment by ggppdk** [comment]
I confirm this is a bug and it is a little more important than a not set variable:

-- Due to trying to use Joomla template overriding
the Joomla module helper function:    JModuleHelper::getLayoutPath()
is including 'default.php' when files tmpl/LAYOUT/header.php tmpl/LAYOUT/footer.php do not exist

You can fix this by also copyin files:
tmpl/news/header.php    as   tmpl/mynews/header.php  
tmpl/news/footer.php    as   tmpl/mynews/footer.php  

Bug fixed in: 09b2830
by adding check if files exist

**Comment by ldoliv** [comment]
Thank you, I apreciate it.
