### ISSUE TITLE
Revise frontend CSS to allow more Joomla template CSS to take effect and allow easier overriding

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#212]
This work has already started.

We are revising frontend CSS to 
- allow Joomla template CSS to style more areas
- allow easier overriding

TODO
- remove unneeded properties
e.g. removed already most:
 font-family

- replace some flexicontent specific classes with bootstrap
e.g. replaced
  'fc_mini_note_box'  with  'alert fc-small fc-iblock'

- Replace all not needed !important with more specific CSS rules, by prepending
.flexicontent or body

**Comment by agata-wdd** [comment]
Hello,
I'm building filters for the categories and I encountered a bit of a problem. When building the filters, I can easily use a custom class for the filter and clear buttons either from the back-end or via an override, however I can't do the same with selects (and possibly with other fields that might be used for filtering a category?), the only thing I can do is wrap them in additional elements using the fields in the back-end. Would it be possible for the selects to be a bit more "exposed" and included in files that can be overridden so I could have more control over their display? Ideally I would like to be able to make the code Flexicontent renders match exactly what I receive from the front-end dev so it could be styled exactly the way he intended and also work with the javascript he provides. I'm already able to do it 99% of the time which is why I love using FC.
Cheers,
Agata

**Comment by ggppdk** [comment]
Easier overriding of CSS was done in v3.0.x, but we can leave this open and examine it more in a later version

**Comment by ggppdk** [comment]
CSS mostly done, we can now open specific issue if needed, closing this
