### ISSUE TITLE
Universal module custom templating, unable to get the all image path/urls from a multivalue image field

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#222]
Hello,

I'm using the latest build, I had already reported this issue but it was closed.

I'm placing the field in the univ. flexi module in the select fields section. In the php code I'm forcing to render the image with FlexicontentFields::getFieldDisplay($item, 'product_gallery'); but the thumbs_src parameter only has the 1st image. I know that in Flexi v2 thumbs_src had all the images.

To get the images I have to:
$multiImage = $item->fields['product_gallery'];
$totalImages = count($multiImage->value);
$multiImageParams = $multiImage->parameters;
$multiImageDir = $multiImageParams->get('dir');

for ($x = 0; $x < $totalImages; $x++) {
     $imgData = unserialize($multiImage->value[$x]);
     $imgFileName = $imgData['originalname'];
     $largeImgPath = $multiImageDir . '/l_' . $imgFileName;
}

Where as before I could just do: $largeImgPath = $multiImage->thumbs_src['large'][$x];

Issue number 2:

In the module the field 'display' parameter always shows only the 1st image and the total number of images, changing the setting in the field's options does nothing.

Same if I place the field in the template item view, always shows all images independently of changing the setting in the field's configuration.
![image](https://cloud.githubusercontent.com/assets/6535818/7887901/6528ccc8-062c-11e5-9f01-51ecec3630c9.png)

Please check this. I would apreciate it.

**Comment by ggppdk** [comment]
Hello

it was closed because 

there is no bug,
-- module only uses 1 image per item, i don't understand why you call this a bug, the module parameters do not claim  to use multiple image per item, there is no such description


- to access all images in a custom made universal module template you can use:
$item->fields['product_gallery']


-- question,
why have you opened a new issue,
- you can respond to the original issue, or you are not permitted to respond?


For future version we may have option for carousel template to make slideshow of single item, using all images,
-- but this is can be an enhancement issue and not a bug issue

**Comment by ldoliv** [comment]
I didn't know that I could repond to a closed issue.

My questions:
1. So were there changes made to the code? because before I could access thumbs_src parameter that had all images. It was a matrix having thumbs_src['large'][0], thumbs_src['large'][1], thumbs_src['small'][0]
2. Is the above code the most correct way to get all images from the field?

**Comment by ggppdk** [comment]
Yes there are relevant changes,

that may have effect this change in behavior,
- e.g. we do not want to add the 
Gallery JS / CSS code,

when just wanting to display a single image in module,
-- but in any case all thumbnails should be all be available,
so the src array should be populated

will change this to a bug with v3.0 milestone

**Comment by ggppdk** [comment]
Please test and confirm the fix, and post back (to this closed issue)

**Comment by ldoliv** [comment]
Yes, thank you, that fixed it :)
