### ISSUE TITLE
Form has expired warning when using forward / back browser button

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#280]
Hello, I'm using chrome browser version "45.0.2454.85 m", but I also get this issue when using firefox.

Joomla! 3.4.1 and FLEXIcontent version 2.2.0 stable

1. I submit the search form with some fields (Category view)
2. Use back browser button and get the message:

"Confirm Form Resubmission 
ERR_CACHE_MISS"

I get this message asking me to refresh the page, even if I go forward I still get this message and it is very annoying.

I found that it works well by enabling the option "Disable cache (while DevTools is open)" in chrome dev tools.

Is there any way to avoid this by forcing form resumit in flexicontent php code, when doing back / forward using browser button?

Found this: http://superuser.com/questions/341792/disable-confirm-form-resubmission-prompt-on-google-chrome

Does a more recent version of flexicontent fix this issue?
Please give feedback.

**Comment by ggppdk** [comment]
yes have tried all these solutions in v3.0.0 and they worked 

- but if we ask the browser to cache it, this will result in user seeing the same result after login / logout
so the workaround was not added in v3.0.0, 

adding an extra variable to the URL: logged=1
does not solved the back button problem

- is it acceptable for the user to see wrong data if he clicks back
e.g. he logs out he click back and he sees items allowed only to registered members

**Comment by ggppdk** [comment]
e.g. see here the back button and the logout issue:
http://stackoverflow.com/questions/10330336/after-logout-click-on-back-button-cache-issue

**Comment by ldoliv** [comment]
The website I'm working on there is no login session, user does not log in.
I have a category view with filter search.
For this situation couldn't your solution be applied? And ignore it for user login sessions ?

**Comment by ggppdk** [comment]
i have given this v3.0.8 milestone, will enable browser caching via parameter, that will be OFF by default

**Comment by ldoliv** [comment]
Thank you :) appreciate it

**Comment by ggppdk** [comment]
Read here why we need to be very careful with browser caching and proxy caching and content of logged users
https://code.google.com/p/doctype-mirror/wiki/ArticleHttpCaching

It is ok to use for unlogged users
- to allow both browser and (MAYBE) proxy caching ***

For logged user content, 
- allow browser caching 
- and disallow HTTP proxy caching

The google docs have details on how to do it, 
- and doing it wrongly is an important security risk

also it seems that the only safe way to load different page for logged users
- either not use browser caching
- or use different URLs to make sure browser will re-download page after login, 
even using JS to do a page reload will require loading a different URL


*** Finally proxy caching is bad idea in all cases because,
if a website with FLEXIcontent has 3rd party modules or plugin 
- that use cookies to track guest content
and we enable proxy caching !! then we will break these and it also a security issue too


In the end it seems to always try 
- to always avoid proxy caching, 
and not only avoid it, but also force it to be OFF with an expires age in the past,
and then using a positive 'max-age' in cache-control header to tell browsers how long to cache

**Comment by ggppdk** [comment]
The result is better than i expected

Added browser caching support with commit 012bfde, this includes 
- browser caching for public (unlogged user) 
- browser caching for multiple users logging from same browser (logout/relogin)
- proxy caching disabled to avoid issues with 3rd party extensions doing per guest content via cookies,
- auto-reload page after login/logout support and when back/front buttons are clicked
- browser history replacing is done after login / logout and when back/front buttons are clicked

2 purposes were achieved:
- mainly avoid page expired message in back/front buttons
- but also increase front / back buttons speed by avoiding text search / filtering form to be-resubmitted since now pages are browser-cached
