### ISSUE TITLE
About enlarging back-end templates view

### ISSUE THREAD

**Issue by julienbenisty** [FLEXIcontent/flexicontent-cck#281]
When landing in the templates view of the back-end, the top information table and the actual templates tables are not showing full width. Which compact the info and wasting screen estate.

First fix:
/administrator/components/com_flexicontent/views/templates/tmpl/default.php

On line 73, change
```
<table class="fc-table-list" style="margin:0px; min-width: unset;">
```
for
```
<table class="fc-table-list" style="margin:0px; width:100% !important">
```

Second fix:
/administrator/components/com_flexicontent/assets/css/flexicontentbackend.css

On line 138, change
```
.flexicontent #adminForm table.adminlist {
	width: auto !important;
}
```
for 
```
.flexicontent #adminForm table.adminlist {
	width: 100% !important;
}
```

I tested these 2 fixes on modern browser on Mac (Chrome, FF and Safari).

**Comment by ggppdk** [comment]
thanks for suggestion,

- but it was like this before, and it was changed, because it is difficult to use full width table in large resolution and in UHD monitors (3840×2160)

i think we can try to add some css to prevent wrapping, can you explain where the wrapping occurs ?

**Comment by iamrobert** [comment]
I personally prefer 100% width.

If we look at browser screens, the average user screen is not going to 
exceed 1920px width:
http://gs.statcounter.com/#all-resolution-ww-monthly-201507-201508-bar

Could it be possible to set a max width?

.flexicontent #adminForm table.adminlist {
width: 100%;
max-width: 1800px; //some-value
}

Cheers,

Robert Stark
Web + Graphic Designer
http://www.iamrobert.com
0918 44 88 24

**Comment by ggppdk** [comment]
we would not want a general max-width, other backend manager can benefit in larger screens, we may apply max-width only in templates manager screen

**Comment by ggppdk** [comment]
which column
in the table of templates manager is wrapping the text ?

i mean width auto should allow the table to expand

**Comment by julienbenisty** [comment]
not sure what you mean by "which column in the table of templates manager is wrapping the text ?" ?

I would also go with a width/max-width approach. Even if it's inline in the view file.

here is a screenshot:
![templates-table](https://cloud.githubusercontent.com/assets/381525/9784848/28b15564-57d8-11e5-8515-d8f1d5ede1a1.png)

**Comment by ggppdk** [comment]
Will close this, as i don't see something broken or wrapping in the picture you posted, and forcing this table in very large screens to 100% make more difficult to read (i am using a big UHD monitor and it does make it hard to read)

the 100% width in backend views was removed deliberately, because
- of how it looks in very large screens
- and combined with the fact that in many screens you can remove/hide columns (imagine 3 columns with 100%)

if you visit other backend screen and you hide columns, you will see that the tables are not forced to 100%
- if you still think this is important, we can add a min + max width to it, and reopen this issue
