### ISSUE TITLE
Dashboard Revised items slider (waiting for version approval) only shows 1 item

### ISSUE THREAD

**Issue by toowoombarc** [FLEXIcontent/flexicontent-cck#317]
/administrator/index.php?option=com_flexicontent

Slider: "Revised, waiting for version approval"
This only shows one(1) item when the count is actually one(1) or more. I want this to act like Slider: "Draft :: Unpublished, Waiting to be written" where there is more than one(1) item showing in the Slider view at any given time.

Kind regards,

**Comment by ggppdk** [comment]
thanks for report, yes it is as you describe

this was recently fixed (3 days ago) with commit 8b149c8,

The commit:
- fixed "Revised" slider showing only 1 item
- fixed dashboard sliders showing wrong total count of items
- fixed ordering to be most recent first

these were introduced when we optimized queries for large websites,
- will leave this open till v3.0.9 is released, for other fixes since v3.0.8 you can see the github commits log

Unless very sure of a bug, you can first report the issue at our forums:
flexicontent.org/forums

**Comment by noxidsoft** [comment]
Can advise that [8b149c8](https://github.com/FLEXIcontent/flexicontent-cck/commit/8b149c83a4440e7468461010164dea2932e76101) works well, I have notified toowoombarc (issue owner) and tested on their instance. Consider fixed.
