### ISSUE TITLE
Fieldgroup values not restored using version history

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#361]
Version restore for me isn't working for fieldgroup values. I'm using FLEXIcontent 3.0.9-rc3.
Is this implmented ? If not please add this to a milestone.

**Comment by ggppdk** [comment]
i have not tested this, it should work, because the storage for field group values is same like other fields , except for the fact that field values may contain holes in the numbering, 

if not it should be easy to fix,
- i am thinking it is because of the new field value column that we added "suborder", it is probably ignored by the version restore code

**Comment by ggppdk** [comment]
milestone v3.0.9 (next 2 days), as this should be easy to fix and this is maybe the last fix for v3.0.9
- but please note that:  The fix may work only for versions saved after the fix
i will say more after testing / fixing

**Comment by ldoliv** [comment]
Ok, please check and thank you

**Comment by ggppdk** [comment]
Fixed with 1875d91
