### ISSUE TITLE
Image field: issue with positioning preview thumbnails in item form

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#404]
I have noticed some issues with the image field in the backend:

1. The thumbnail is fixed to 120x90 pixels
2. It uses the size for small thumbnail, not the size for backend thumbnail

This causes some ackward empty space when your small thumbnails are significantly larger than 120x90:

![](http://i.imgur.com/Q7WwlvS.png)

I will send a commit to fix this

**Comment by ggppdk** [comment]
I think we will need to revert this commit

Because backend is mainly for backend items manager,
- the item form displays in both frontend and backend, so backend thumbnail is not appropriate

Maybe it is best to 
- add an new SET of parameters "Item form thumbnail" ?
- or to add less parameters, maybe add a single parameter, called:
"Select thumbnail for item form" ?

About space i don't know without viewing the CSS of the page,
is it with default joomla backend template ?
are the any other CSS files being loaded?

**Comment by ggppdk** [comment]
Also changing a thubmnail size will not make difference
instead the actual CSS positioning issues should be addressed

**Comment by ggppdk** [comment]
Ok i found, the effect that you are seeing is because of a CSS rule for image preview container

**Comment by ggppdk** [comment]
Fixed with: 4df67a5

- added preview thubmnail size (width / height parameter) into the "Editing" Tab
- for performance reasons they are required to be up to the size of "Medium" Thumbnail and phpThumb will use/read Medium Thumbnail for creating the preview thumb, if a larger value is added then image will be scaled up and look ugly (a inline note was added, but now i think we should force it into the code too)
- fixed the CSS rule too
