### ISSUE TITLE
Add option to turn off email cloaking in email field, aka insert real email links

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#424]
Should we add a configuration option to control whether we want to render link and force email cloaking?

In this line:
```
$html = $format != 'feed' ?
	JHTML::_('email.cloak', $addr, 1, $text, $text_is_email) :
	'<a href="mailto:'.$addr.'" target="_blank" itemprop="email">' .$text. '</a>';
```
https://github.com/FLEXIcontent/flexicontent-cck/blob/master/plugins/flexicontent_fields/email/tmpl/value_default.php#L28

We have a situation where we need email addresses to be rendered explicitly, and with a link. I can make the changes and submit for your review.

**Comment by ggppdk** [comment]
Yes this can be desirable in some cases,
and i think we can commit this directly, no pull request for this,

- just let default behaviour be the existing behaviour

Changing default behaviour (i don't mean default styling) should be done only if really needed (= important feature / security / bug that is not possible to fix otherwise / etc),
- otherwise it frustrates users trying to reconfigure the component after upgrade, or considering it a bug, e.g. cloaking stops working after upgrade will seem also seem like a bug

i will test it too, after you add it

**Comment by Lyquix** [comment]
I just made a commit with the discussed changes 014428c.
The default behavior is the same we had before the change.

**Comment by ggppdk** [comment]
Tested, new options to disable cloaking and email linking works properly, closing
