### ISSUE TITLE
Merge sharedvideo and sharedaudio fields into single field named sharedmedia

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#425]
The fields sharedaudio and sharedvideo are almost identical right now. This enhancement has three parts:

1. Create a new field named sharedmedia that will combine the functionality of sharedaudio and sharedvideo and will allow users to embed either audio or video players
2. Remove sharedaudio and sharedvideo fields
3. Update the installation scripts to automatically convert any data and fields to the new field type.

**Comment by ggppdk** [comment]
Merged with sharedmedia with last commits, and finally removed/replaced them with: a28ffc2

Also in last commits fixed / finished field group support, made JS functions to be 1 per field instead of 1 per field value, also layout of fields and preview is now more responsive like for "addressint" field. Re-enabled native APIs support, (by default it is disabled) and made some other minor improvements, like selecting to only show META data of video/audio instead of allowing edit always

**Comment by ggppdk** [comment]
We made a mistake,
- if a user does not have API KEY, and he clicks "save" then OLD video/audio data are lost
- that is because the form does not post the old data

i will open a new issue for this and address it,
if API key is missing then the form must still load and display old data
