### ISSUE TITLE
Add warning that changing field-name will effect configuration that references field by field-name

### ISSUE THREAD

**Issue by bropa** [FLEXIcontent/flexicontent-cck#458]
After changing name of field (not label), this field will be unselected/removed of all places where it was selected (in template field placement, category settings and so on ...)

FLEXIcontent 3.0.13 
Joomla! 3.4.8

**Comment by micker** [comment]
Its not bug its normal behavior

On ven., févr. 12, 2016 at 1:33 PM, bropa < notifications@github.com [notifications@github.com] > wrote:
After changing name of field (not label), this field will be unselected/removed
of all places where it was selected (in template field placement, category
settings and so on ...)

FLEXIcontent 3.0.13
Joomla! 3.4.8

**Comment by bropa** [comment]
Maybe its normal, but uncomfortable ;)

**Comment by ggppdk** [comment]
In some parameters it field NAME and in some it is field ID

**Best it would to use field NAME in parameters and not field ID**

- because we are implementing:
type/field/etc **configuration EXPORT/IMPORT** in v3.1

and using the ID makes **importing** more difficult, because after importing the parameters have to be read and do some remapping of the IDs used in the current DB, thus we are making a list of parameters that use IDs, and finishing the remapping code so that the import will work (not finished YET)

**Comment by ggppdk** [comment]
Hmm, but we do need to add a more clear -inline- warning or a warning icon with a popup, so i am leaving this issue open to add this

**Comment by ggppdk** [comment]
Added UI warning with 781b195
