### ISSUE TITLE
Very slow opening and saving categories when there are many templates

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#529]
This seems to be a bug or something that needs optimization. We are experiencing very slow opening and saving of categories, items and content types. We are working on J3.5.1 with FC3.0.14rc2.

It seems to be related to the number of templates that we have on the site. We have a custom template that has a large number of fields, and we have several copies of the same template with different configurations for different categories and content types.

The problem is most evident and disrupting when working with Categories. In general it takes very long for categories to open, and to render the page, but the most problematic is saving: when we click Apply/Save on any category the gray overlay, and the "Form is being submitted" progress bar are displayed, and it stops there. Very often Chrome shows an alert indicating that the page has crashed. It takes between 60 and 90 seconds for the page to unfreeze and then the progress bar starts filling.

To get some concrete measurements, I tested on a fresh installation and I don't see the problem. I tested assigning our template and it is not a problem. But when I created copies of the template the problem become visible. 

Here are some numbers, running from a local VM as measured by Chrome:

Only FC original templates:

Category Open: 3.48s
Category Save & Close: 0.639s (no perceptible wait time)

With 10 copies of Lyquix "custom" template

Category Open: 12.39s
Category Save & Close: over 10s wait + 0.688s

With 20 copies of Lyquix "custom" template

Category Open: 25.58s
Category Save & Close: over 28s wait + 0.530s

It looks like there is some Javascript process that is executed at load and before save that grows by the number of templates available in the system. Perhaps this can be optimized.

**Comment by ggppdk** [comment]
Yes exactly, already know about this, and all details of it too

and it is not in **category form only it is item form too**
and it is because we are loading the parameters of all templates 

the slow down depends on 
- the **total number of layout parameters**

it has always been like this, and parameter loading needs to be AJAXIFIED
- like field parameter loading in field edit form
- like layout parameter loading in universal module

more difficult work is the optimization of templates parsing in frontend (XML / LESS / INI) files that was done in v3.0.13 - v3.0.14-rc3

i know how to do it, i have added v3.0.15 milestone, although it may be pushed to 3.0.16, this was the last thing i was not happy about during v3.0.13 - v3.014 optimizations, wanted to include it but it was not trivial work ... the good things is that we have the AJAX code of 
- field parameter loading in field edit form
- layout parameter loading in universal module

so things we most work is already done

**Comment by ggppdk** [comment]
In your case you are using custom templates that have a lot of parameters, and that is why you are seeing a magnification of the effect

**Comment by Lyquix** [comment]
Is there something I can do to help? I think during Save, we might be able to optimize JS so that it doesn't go through fields for all templates (only one template is selected).

**Comment by ggppdk** [comment]
You speak of JS delay due to JS validation ?

- it is HTML5Fallback.js that is not optimized, but in J3.5.2 its validateForm() is not set to run ...
about validate.js include with FC it is already mostly optimized

**Comment by Lyquix** [comment]
Yes I am talking about the JS delay. To me that's the big issue here. I don't know what exactly is causing the delay, but maybe on save, we can skip anything that is being done with fields from templates that are not selected.

**Comment by ggppdk** [comment]
Actually i have been doing extensive work on JS files lately (on the validation code and other), profiling performance too,
- will make a PR for Joomla findLabel() performance and some other JS stuff

FLEXIcontent JS validation code is already mostly optimized (we do override Joomla validate.js) 
- the delay that you see is by Joomla's html5fallback.js (function validateForm()) which we do not override
- but it seems Jooomla 3.5.2 will not use validateForm()  of it (of html5fallback.js)

now about v3.0.14 is finished, 
- but i will only include my recent changes to JS code

(i think to also include an override of html5fallback.js)
and then will release 3.0.14, 
- after it, will immediately work on making layout parameters loading to be AJAX based

**Comment by Lyquix** [comment]
Thank you @ggppdk ! Let me know if we can help with anything!

**Comment by ggppdk** [comment]
- done with JS validation optimization
- done with AJAXifying relation field, 
- almost done with AJAXifying the layouts in forms: item / type / category

indeed the forms will now behave well in large website and in site with many templates

you will commit today or tomorrow, you can then test

**Comment by Lyquix** [comment]
This is great! We will test and provide feedback.

**Comment by ggppdk** [comment]
Fixed with 7dc3052

Please test:
https://github.com/FLEXIcontent/flexicontent-cck/tree/3.0.x-stable

**Comment by ggppdk** [comment]
Fixed with 7dc3052
Now 
- form performance will not be effected by number of templates
- improved display of inherited parameters, after you save form, then it will appear for layout parameters too, thus making layouts more easy to configure

Please test:
https://github.com/FLEXIcontent/flexicontent-cck/tree/3.0.x-stable

**Comment by Lyquix** [comment]
Works very well! I love the Fast Apply!
Thank you!

**Comment by micker** [comment]
if we didn't find any problem i recommend to remove basic save for fast apply

**Comment by ggppdk** [comment]
I have made 1 more optimization for all forms that use FC layouts 
(item / type / category)
- a measurable benefit will be seen if having 10+ or 20+ templates

also a change specific to category form
- the optimizations further optimize form-loading
