### ISSUE TITLE
Breacrumbs incomplete path when using FC load module field

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#536]
Hello guys, we are observing an issue with incomplete breadcrumbs showing incomplete paths when the module is rendered using an FC load module field.

The setup:
* Menu item for a category view
* Item view includes a field of type load module used to render the breadcrumbs

The problem:
* The breadcrumb renders: Home > Category
* If I add the module to a regular position, it renders: Home > Category > Item

We use the following code to get the content of the pathway in both cases:
```
$app = JFactory::getApplication();
print_r($app->getPathWay());
```

We insert this to the FC load module field and we get:

```
object(JPathwaySite)#968 (2) {
  ["_pathway":protected]=>
  array(1) {
    [0]=>
    object(stdClass)#969 (2) {
      ["name"]=>
      string(35) "Orthopaedic Specialties & Services "
      ["link"]=>
      string(64) "index.php?option=com_flexicontent&view=category&cid=2&Itemid=142"
    }
  }
  ["_count":protected]=>
  int(1)
}
```

and when we insert it in the Joomla module, we get:

```
object(JPathwaySite)#968 (2) {
  ["_pathway":protected]=>
  array(2) {
    [0]=>
    object(stdClass)#2067 (2) {
      ["name"]=>
      string(34) "Orthopaedic Specialties & Services"
      ["link"]=>
      string(13) "/specialties/"
    }
    [1]=>
    object(stdClass)#2228 (2) {
      ["name"]=>
      string(3) "Hip"
      ["link"]=>
      string(16) "/specialties/hip"
    }
  }
  ["_count":protected]=>
  int(3)
}
```

You can see in the second case the breadcrumbs include an additional segment, and URLs are already SEF.

Is this something related to Joomla's execution sequence? Is there anything that can be done?

Thank you!

**Comment by ggppdk** [comment]
@Lyquix 

so you we get less **pathway segments** if we render the breadcrumbs module via the 
**load module field**

#### Example of pathway via using module manager (to create the breadcumbs module)
Menu Item / Category name / Item name

#### Example of pathway via using load module field to load the breadcrumbs module
Menu Item

**These are missing**
Category name / Item name


- yes this is an issue bug
- there is an explation for this, it is because 

**view.html.php of item and category view, adds the extra pathway segment AFTER we create flexicontent fields**


#### Our views create the fields with calls like this e.g. item view
```
FlexicontentFields::getFields($_items, FLEXI_ITEMVIEW, $params, $aid);
```

we can try to move the addition of extra segments above it, 
- that is if nothing else gets broken by this move, which i think nothing will break

**Comment by Lyquix** [comment]
Excellent! I will test the change and inform you of the result
