### ISSUE TITLE
hide label of empty filter

### ISSUE THREAD

**Issue by germanybw** [FLEXIcontent/flexicontent-cck#537]
Hi

I think, it`s a good idea when the labels of empty filters (filters with no available values) not be displayed.

I think, In case there are many filters in a category, empty filters with no available values and only a label confuses users and need too much space.

**Comment by ggppdk** [comment]
Actually you imply something the filter values
about non-available values we have 2 options:
- hide (skip them)
- show as disabled

So when
1. We have enabled option:
"Hide non-available values"
2. Zero available filter values are found

then we should also hide (skip) the filter label

**Comment by micker** [comment]
good idea, after this it will be more simple to configure filtering via global config
1 allow all and hide if no value inside in global config
=> that done for all categorie
:+1:

**Comment by ggppdk** [comment]
Added (or "fixed") this with c88a5d8

https://github.com/FLEXIcontent/flexicontent-cck/commit/071b8b6b9e2db8663c666d6e18cf52a0da3455c3

To test (if parameter is hide value is enabled)
open this URL , save as , and backup + replace the file
https://raw.githubusercontent.com/FLEXIcontent/flexicontent-cck/3.0.x-stable/site/classes/flexicontent.fields.php

**Comment by germanybw** [comment]
very much thanks for your very fast and great solution. 
It work great.

**Comment by ggppdk** [comment]
About very fast fix,
- it is because fix was very small, it is an empty if statement

1. No parameter needed to be added (already have a relevant parameters as i said above)
2. Filtering code in both **search view / category view** was already written so that it skips filters that return no HTML
3. I already knew where to look

otherwise i would have looked at this, during next 7 days (estimation)

**Comment by germanybw** [comment]
Sure, not every problem can be solved immediately. Nevertheless many thanks.
