### ISSUE TITLE
Add "Exclude some types" option to next/previous navigation field (fcpagenav)

### ISSUE THREAD

**Issue by mshou** [FLEXIcontent/flexicontent-cck#544]
Hello
Im using Joomla! 3.5.1 with FLEXIcontent 3.0.14-rc2a 

In FLEXIcontent v3.0.10 release, next/previous navigation field (fcpagenav) was improved and the "Exclude some types" was removed from field configuration. How can i do it now? 

(navigation field (fcpagenav) with FLEXIcontent 3.0.9-dev )
![image](https://cloud.githubusercontent.com/assets/15908034/15212859/2cbeaff2-183b-11e6-815a-2cc887b481d5.png)

**Comment by ggppdk** [comment]
You can do it ... read on ..


About changes in field: Next/Previous item (fcpagenav)
- it was optimized for high performance

but the above is not the reason for removing the exclude types is
- we now display the **same items** as category view,
in order to do the above we now display the items according to category configuration

so you can go to category edit form (or to a top-level category so that you effect subcategories)
- and in locked filter values, set a locked value for the "type filter" to specific (multiple) types

**Comment by mshou** [comment]
Locked filter works for category view but the navigation field still includes all articles.
Can you please check ?

**Comment by ggppdk** [comment]
I forgot to say that if you change the category configuration

- then it will not work immediately

because of caching about 100 items ids and current navigation inside user state, you will need to close browser window

the reason for using user state is 
1. because every user maybe able to see more items according to user's view access levels and 
2. maybe to avoid joomla cache growing larger decide not to use Joomla caching and used user state instead
