### ISSUE TITLE
No Publishing tab in backend item edit form [because it uses ACL privilege "set params"]

### ISSUE THREAD

**Issue by Lyquix** [FLEXIcontent/flexicontent-cck#554]
We are observing that non Super Users don't see the Publish tab in the backend item edit form, and therefore cannot handle the created, publish up and publish down dates.

We have a custom user group with the following permissions set to Allowed:

Global: Items (Item edit Form): edit creation date, and Items (WorkFlow): can publish document changes regardless of edit state
Category: all permissions
Type: all permissions

In Global configuration, under Item Form > Publication Details is set to Basic. The same setting in all categories and types is set to Global.

**Comment by ggppdk** [comment]
The need the ACL privilege (inconsistency with frontend):
item form : "set params"

Then **creation date** also needs ACL privilege:
item form "edit creation date"

**Comment by ggppdk** [comment]
1. We need to change the name "set params" to "edit publishing details"
2. For frontend item form we need 1 more parameter, "Use ACL for publishing TAB", which will have default "No"

**Comment by Lyquix** [comment]
Ahhh thank you! :-)

**Comment by ggppdk** [comment]
So we have/use these special ACL for:
- Access ('**set access level**' ACL)
- Created date  ('**edit creation date**' ACL)
- Created by  (**is-superAdmin** ACL)

For the others:
- Publish Up / Down
- Created by alias (=author name alias)

**we use the "set params" ACL privilege**, but Joomla uses "edit.state",
- will do this: will remove the "set params" and use:

"edit.state"
"edit.state.own"   (which currently Joomla does not have)

Because it makes sense, that **if a user can publish / unpublish** an item (edit.state(.own)), then user should be able to set:
- Publish Up / Down  (and His/her/* author alias)
