### ISSUE TITLE
Feature request: Templating for front-end forms

### ISSUE THREAD

**Issue by JeBy777** [FLEXIcontent/flexicontent-cck#603]
Hi there,

I'm loving the templating options becoming available for fields, etc. 

Wouldn't it be a good idea to allow templating for front-end forms? I now have to edit the form.php file to make it look different (I made it more bootstrap compliant) but it obviously always falls back to the old form.php when I update my flexicontent to a newer version. What do you think?

Thanks again for all your hard work!

**Comment by ggppdk** [comment]
About layouts in fields, v3.1.0-rc
- 1/5 of fields already allow layouts for **item form**
- 4/5 of fields already allow layouts for **item view**

TODO the rest, and there was good reasons for delaying this, delay was
- in order to finish advanced field-group support 
- and "depends on master field" feature (* a little more work is needed here ... e.g. hide fields)

About layout specifically for frontend form
**you can fully customize it**,
**without template override**
- using the parameters in type form  (customize top-level tabs)
- using the **item-form field** "Tabset / Fieldset / Custom HTML"

TODO: create a multi-step form, and will doing this, will see to revise configuration UI of form layout
