### ISSUE TITLE
Adding icons in select list

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#645]
relevant to this topic http://www.flexicontent.org/forum/9-support/55288-affichage-des-articles-sur-la-premiere-page.html#64379
adding font answone or bootstrap icon in select list end multiselect list
i found some return about this here http://stackoverflow.com/questions/17118025/add-icons-to-options-in-select2

**Comment by ggppdk** [comment]
Since everything except for display is already implemented for the other similar fields,
adding this should be little or very little work

**Comment by micker** [comment]
maybe it's a little more work to add in modal editing view .. maybe you can use my icon element (in flexiadmin module)
https://github.com/micker/mod_flexiadmin/blob/master/elements/iconlist.php

**Comment by ggppdk** [comment]
hhmm yes, now the current editing is asking to write the **image filename** or the **font-icon classname**

This is a different topic, but i guess it is easy since you have created the form element already

So if selecting 
- font-icon classname, then we use the form element you linked above for selecting icon,
- and if it is image filename then we use joomla filename listing element

and of course we add for all 6 "selection" fields (code is the same for all of them)
