### ISSUE TITLE
Image field filename handling bug

### ISSUE THREAD

**Issue by lyquix-owner** [FLEXIcontent/flexicontent-cck#660]
I just encountered the following major bug in FC 3.1.0 and J! 3.6.4

When uploading an image file name, the file name is changed to lowercase, but this change is not reflected in the database, causing thumbnailing to fail, images to not be displayed, and error displayed in backend (file not found).

I have also noticed that spaces are not converted to dashes anymore.

**Comment by ggppdk** [comment]
Yes a fix for this, has already been commited

you can install current github repository,
it is good and will be v3.1.1 after 1 more ifx

**Comment by ggppdk** [comment]
Bug fixes since v3.1.0:

- bug fix for multi-property re-voting (race conditions in DB update) + better styling
- bug fix for capital letters in image field in DB mode
- bug fix for PNG transparency issue (some servers)
- bug fix for "required" textarea / description fields, when you click TOGGLE editor OFF button
- bug fix for universal module date scope when using date field that has no timezone, it will now compare to server localtime

**Comment by lyquix-owner** [comment]
Thanks @ggppdk !
