### ISSUE TITLE
Basic / expert view

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#68]
insert a button to switch all admin view to basic => expert view
save state bewteen page change
ex :
-items view : 
basic view : hide more column hide radio button on search, hide mode filtering => cleaner view
expert view : actual view
-item view 
basic view : hide compatibility tabs, template tabs etc => cleaner view
expert view : actual view
-ategory view : hide peer category notification etc ...
basic view = basic common usage

**Comment by micker** [comment]
other idea custom option
and maybe an option in user option to set default by user

**Comment by iamrobert** [comment]
Here's my thoughts. One of the things I am finding with FLEXIcontent is clients struggle finding or resetting items + filters - I know its powerful - but:

1. Clients don't add content that regularly - so trying to sort it out is difficult - sometimes its like "where's waldo?" if you give people too many options.
2. 50% of internet traffic is already mobile - by 2018 - 80% of the world will own a smart phone - so I believe it needs to work on a smart phone - so that means choose which is most important.


![word](https://cloud.githubusercontent.com/assets/8617673/5616950/42c4bfa6-9544-11e4-9f41-b23f537d9215.png)

I think the only filters clients require are:

1. Search - do they need intro text content?
2. Order type - do any clients switch from FLEXIcontent to Joomla? What's its purpose?
3. ID - only developers need it
4. Search by Image - its nice but I am trying to think how often anyone would need or use it?
5. I really feel the state groups should go into the Status drop down - people search for published/unpublished/trash
-----------------------------------------
Think we need a reset button like Joomla - that resets everything as well.

I am putting a new version of my template together - so I will be arranging it a bit differently:

![joomla](https://cloud.githubusercontent.com/assets/8617673/5617197/fb13c5c8-9546-11e4-9e03-2edd62eb7410.png)

**Comment by micker** [comment]
I am agree we study a solution for this

**Comment by micker** [comment]
Can you propose a pull request with your css for dropdown ?

**Comment by ggppdk** [comment]
@iamrobert 
thanks for the suggestions, will do those that need less work now !
e.g. about CLEAR button , i totaly agree !

**Comment by micker** [comment]
news css for dashboard is on road
TODO :
-need new style for slider

**Comment by iamrobert** [comment]
I like the new dash board. Here's my attempt:




-- 
Robert Stark
Web + Graphic Designer
http://www.iamrobert.com
0918 44 88 24

**Comment by micker** [comment]
![Image of dashboard](https://lh6.googleusercontent.com/-s0dspBcXcOM/VK0_1JD5WfI/AAAAAAAAGIM/Q9QRdb7Rrv8/w1598-h564-no/dashboard.png)

**Comment by iamrobert** [comment]
Sorry - here's my attempt:
![download](https://cloud.githubusercontent.com/assets/8617673/5658188/88468866-9738-11e4-9a90-fc3b78a816c7.png)

**Comment by micker** [comment]
in my screen we didn't have slider because we can hide or show it (and all orther button)

**Comment by ggppdk** [comment]
Almost implemented

state group will be merge with "state"  (now called 'status')
and 'category state' will be a new filter, the STATE box will be removed

**Comment by micker** [comment]
:100:

**Comment by micker** [comment]
i think that we plan is good for form and admin list view (tabs order + styling etc)
the last work i think is :
-create a script to hide tabs, fieldset, field => after we can use it to hide less used option for simple admin 
-create a button to switch between simple and advenced admin
-store choice in cookie
=> after this i this we will have the best admin !!! thanks for your effort
