### ISSUE TITLE
Enhance CSV import to do export and also do import of existing items (aka update)

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#71]
Currently CSV import although powerful it does not allow:
- exporting items
- importing existing items (aka update)

this would be useful for various usage scenarios

**Comment by ggppdk** [comment]
- changing milestone to v3.0.10, at least for "basic export"

since:
- we already have export code for XML, CSV, SQL thanks to 3.1-dev

the import and updating existing maybe done later in v3.0.x, or v3.1

**Comment by l-arnold** [comment]
Very important request.  Clutters your database if you always have to import into a new Item Set rather than updating an existing item.  

For instance, one may add Galleries or new Fields to certain Item types.  Doing so would mean that every existing item needs a new import applied.

Export is helpful for a variety of reasons, one among them is simply to see the type of file which is actually needed for importing.

**Comment by iamrobert** [comment]
@micker Has CSV import/export been completed? I'm looking for a tutorial.

**Comment by micker** [comment]
Yes that works ! You Can find tuto in flexicontent site
