### ISSUE TITLE
How to avoid "Update temporary item data" for sites using com_content together with com_flexicontent ?

### ISSUE THREAD

**Issue by woluweb** [FLEXIcontent/flexicontent-cck#730]
Hi !

Typically, on websites where I have Flexicontent, I leave com_content because it is easier for the end-user when they want to edit their articles.
(Only the "items" are managed by com_flexicontent)

But then, some issues can happen, like a pure article which is modified but not taken into account.
When one goes to com_flexicontent in the backend, he/she will see a "Update temporary item data" button.
That does solve the issue.

But as web agent, I don't manage the content so I never to to the Administration (and even less to com_flexicontent once the site is launched).

So is there some solution or workaround (like a cron job, disabling some flexi cache, or whatever)  in order to avoid that "Update temporary item data" ?

Txs !
And congratulations for the presentation on #jd17fr and for the preparation of the quickstart.
That will be a killer !

Marc

**Comment by ggppdk** [comment]
> So is there some solution or workaround (like a cron job, disabling some flexi cache, or whatever) in order to avoid that "Update temporary item data" ?

Yes, it is time to full support Joomla article form too

We need to add onContentBeforeSave method to our system plugin 
and check if current saving context is 'com_content.article'

```php
public function onContentBeforeSave($context, $item, $isNew, $data = array())
{
	// Only work on new SQL fields
	if ($context != 'com_fields.article')
	{
		// ... Call backend 'flexicontent' controller to update flexicontent temporary data
	}
	return true;
}
```

**Comment by woluweb** [comment]
Hi Georgios,
That's amazing !!! :-)
Txs for the quick reaction and for the solution.
Looking forward to 3.2.0 ;-)

**Comment by ggppdk** [comment]
@woluweb 

We have added better support for Joomla article form with 36cc30b
- Now flexicontent temporary data will be updated automatically when saving Joomla article form
- Also both Flexicontent item view and Joomla article view parameters will be preserved, when editing with any of the 2 forms  (since we are now validating against both Joomla and FLEXIcontent XML files ! if parameter exists in any of them, then it is preserved)

**Comment by woluweb** [comment]
Txs ! That's excellent ! Together with Yannick's Quickstart, that makes Flexicontent even easier to use :-)

**Comment by ggppdk** [comment]
Also in new FLEXIcontent version
-- we display Joomla fields inside FLEXIcontent item form

But I was thinking 
-- how to add FLEXIcontent fields  into Joomla article form

Instead of releasing FLEXIcontent field individually, which is a lot of work and better do this later

The most easy way is to add them to Joomla article form 
**when FLEXIcontent component is installed**

because Joomla article has events to make this easy

- display / saving fields should be easy (just fields will need small updates)
- we will display the **FLEXIcontent Type selector** inside the article form to be able to select which FLEXIcontent fields to show
