### ISSUE TITLE
Setting inside Menu Item, permanent (aka locked) multiple values for category view filter, do not work

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#732]
I have created a category view MENU item

and configured (inside the Menu Item parameters),
some permanent (aka locked) multiple values for a category view filter

using:

19##viedureseau +++ divers

=> that only display item how field 19 have viedureseau and not divers

same syntax work in universal module

**Comment by ggppdk** [comment]
I see that you have spaces our +++
Currently the code will not remove those spaces 
(this was delibarate but probably maybe we should remove them)

so your values are:
"viedureseau "    (space at end)
" divers"   (space at begining)

that is probably why they do not match

**Comment by ggppdk** [comment]
So can you test without spaces ?

**Comment by micker** [comment]
i remove space that doesn't work
same syntax work on universal module

**Comment by ggppdk** [comment]
Maybe this is the reason,

the locked filter must be of multi-value display in order to use in it multiple filtering values

if locked filter has a configured display e.g. drop-down select , then it will only allow 1 filtering value

the fact that the locked filter is not shown, does not make the filtering code think that it is multi-value
Filtering code does not know if filter is visible or not

**Comment by micker** [comment]
its a multi select value !
and 19##viedureseau+++divers **works in universal module**

**Comment by ggppdk** [comment]
Ok i meant not the field type, i mean the display of its filter,

After changing to multi-value display of filter , then value become usable
