### ISSUE TITLE
Specific caractère are remove on prefix and suffix

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#738]
hello i try
prefix
`<iframe src="//v.calameo.com/?bkcode=`
suffix
`&mode=mini" width="480" height="300" frameborder="0" scrolling="no" allowtransparency allowfullscreen style="margin:0 auto;">`
become
prefix
`iframe src="//v.calameo.com/?bkcode="`
suffix
`&mode=mini" width="480" height="300" frameborder="0" scrolling="no" allowtransparency allowfullscreen style="margin:0 auto;">`

same for openning closing texte

**Comment by ggppdk** [comment]
we added stricter validation lately
it strips html

In your example it is half closed html

Since privileged users are editing fields
we can fix by adding
**filter="raw"**

any other parameters that are like this ?

about parameters
prefix / suffix / open text / close text

i will commit fix

**Comment by ggppdk** [comment]
I was thinking to user
filter="JComponentHelper::filterText"

instead of 
filter="raw"

but it is not appropriate, it will strip html tags that is not "closed" aka "invalid"
which in our case is not desirable to strip the half closed HTML

so since editing field configuration 
- is privileged and by default given to super admins and admins
- is only accessible in backend

we should go for filter="raw"

**Comment by ggppdk** [comment]
Fixed with c6df484 and 7cf2eba
