### ISSUE TITLE
Flexicontent File manager, wrong sorting when sorting via file size

### ISSUE THREAD

**Issue by ldoliv** [FLEXIcontent/flexicontent-cck#757]
Hello,

I'm using flexicontent 3.2.0.1, I noticed that ordering by file size doesn't work properly.
![image](https://user-images.githubusercontent.com/6535818/29209920-ec95db70-7e88-11e7-9ba2-2c1496d01a86.png)

Also I would like to suggest adding the option to order by File usage, so we can easily free up disk space on unused files.

**Comment by ggppdk** [comment]
Hello

will fix the order by size

about usage we were considering adding an AJAX task that will call PHP code to do this
since file usage is for some fields, is inside encoded strings and thus we can not achieve this by plain SQL

for file fields it can be done by just SQL, so maybe we could add column "Usage by file field"
but for other files (i speak of image gallery field) will need an SQL task

and it is actually in our plans to create it

**Comment by ldoliv** [comment]
Ok, good to know, thanks.

**Comment by ggppdk** [comment]
About file size the problem is that these files do not have their filesizes stored in DB

thus ordering will not work, 
when you display them, their real filesize is shown but executing filesize(...)

if you re-index "file-stats" it should work

i think the way to avoid bug reports is to remove display of filesize when it is missing from DB and replace it with a notice icon with tooltip "please reindex file stats"

**Comment by ggppdk** [comment]
When sorting by file size, replaced real file size display with a warning to asking to re-index files statistics
This was done with commit: cb9be4f

Here is a picture of the new warning icon asking to re-index file stats
![re_index_file_stats_needed](https://user-images.githubusercontent.com/5092940/29239710-09581262-7f5d-11e7-9008-af4c0f8f8a68.png)
