### ISSUE TITLE
Is Flexicontent supposed to be used for a 21st century?

### ISSUE THREAD

**Issue by jimiero** [FLEXIcontent/flexicontent-cck#760]
I'm sorry! I know that this may be sound crazy.

But if you check some Flexicontent website pages, page source you'll see a huge amount of javascript/css files loaded, which in this days, where we all know site Speed is very important, is not good.

So I wanted to ask if there are  any plans to optimize those loaded files and maybe load them only when they are required ?

**Comment by ggppdk** [comment]
Our JS is not growing, (a few more KBs in version)
and modern browser now do not have problem handling many small JS files

also our core CSS was gather into a single CSS file
soon we will not need mootools in item form too (95% of code has been)
and some remaining (small JS files) that can be done with jQuery will be removed

furthermore the PHP execution time of FLEXIcontent is heavily optimized
try doing same things with other PHP software

our biggest JS is jQuery
if you want to contribute, please suggest something specific that is not needed

**Comment by lyquix-owner** [comment]
@jimiero : 
can you provide specific examples?
have you checked global configuration and field configuration to disable any js libraries that bother you?

**Comment by ggppdk** [comment]
Please provide something specific of which script is huge or very big

our largest 2 scripts 
are
- flexi-lib.js 66Kbs
- tmpl-common.js 17 kbs

tmpl-common is not worth minifying
but will minify flexi-lib since is much larger than 3.1

about other scripts e.g. facebook or google maps or select2 JS 
if you do not need then do not use in your pages

- mootools is not needed for viewing by flexicontent (except if you for legacy field minigallery)

please open a new issue and speak of a specific script or CSS that 
- is not worth loading
