### ISSUE TITLE
Better sef urls for filters?

### ISSUE THREAD

**Issue by jimiero** [FLEXIcontent/flexicontent-cck#766]
Hello,

I tried to search around but couldn't find something, is it possible in Flexicontent to have better sef URLs for applied filters URLs?

The example currently I see:

uncategorised/?p=all&filter_16=Berlin&cc=8d1fcdff9f55d3faf0e3fa86e419a4a9

Was wonder if can achieve:

uncategorised/Germany/Berlin/?p=all&cc=8d1fcdff9f55d3faf0e3fa86e419a4a9

(Not sure if this part can be also hidden from the url: **p=all&cc=8d1fcdff9f55d3faf0e3fa86e419a4a9**

**Comment by ggppdk** [comment]
No no,

this is critical part of the URL !
- important for 2 reasons

Reason 1:
you see after great effort we now handl browser and proxy caching properly
&cc=this long string

means that are a logged user
imagine removing it and having content meant for this user appear as public content because proxy cached it !

Reason 2:
when you click back in the browser you do not get this bad UX warning "your page has expired !!

Finally 2 notes
- if you are NOT a logged user then the logged &&cc part will not appear at all
- our next planned improvements for URLs is to implement better variables for filtering

thus is instead of &filter_45=car
we can use the field name alias 'vehicle_type':
&_vehicle_type=car

**Comment by jimiero** [comment]
Is there no way to make it just sef like:

uncategorised/Germany/Berlin/?p=all&cc=8d1fcdff9f55d3faf0e3fa86e419a4a9

?

**Comment by ggppdk** [comment]
Hi

as i said we do plan to support  too
&_fieldname=value
e.g.
&_Germany=Berlin

you are suggesting also taking the above 1 step further and doing:

it is possible but we need to avoid conflicts
you see there must be no MENU item with alias
_Germany

if you have a menu item with alias '_Germany' under a menu item with alias 'uncategorised' then things will break

maybe to avoid conflicts we should use 
__Germany with 2 underscores

or just stick to 1 underscore because i do not think that people would create such menu item aliases ?

**Comment by jimiero** [comment]
Google suggests to use hyphens (-) instead of underscores (_) in your URLs.

https://support.google.com/webmasters/answer/76329?hl=en

Also in order to avoid conflicts you can maybe do:

menu-item/search/Germany/Berlin/?p=all&cc=8d1fcdff9f55d3faf0e3fa86e419a4a9

**Comment by ggppdk** [comment]
> Google suggests to use hyphens (-) instead of underscores (_) in your URLs.

i think that is for spliting words, but i guess that there is no problem with using
/-Germany/Berlin/  instead of  /_Germany/Berlin/

**Comment by jimiero** [comment]
why do you need to place  - 

won't it help to remove conflict if adding /search/ next to menu-item name ?

menu-item/search/Germany/Berlin/?p=all&cc=8d1fcdff9f55d3faf0e3fa86e419a4a9

**Comment by ggppdk** [comment]
maybe

but also not that after the last SEF /segment/ that is a menu-item-alias
/menu-item-alias-last/some_view_var1/some_view_var2/

we have variables that are segments that are handled by our router , which tries to understand what the current URL is !!

e.g.
/category-menu-item-alias/item/4571-alias/

and router in some also decides the real view according to the number of segments after
/category-menu-item-alias/

in the above case it is item view
so this should be done carefully not to break existing URLs !!!

**Comment by jimiero** [comment]
@ggppdk so do you plan making this imporvements ?

**Comment by ggppdk** [comment]
There is other work that is planned to be done during next couple of months

it is not , that this is too much work
it is the effort to debug it after implementing it

**Comment by JoshuaLewis** [comment]
+1 for better URL filters. However reviews are much more important. Perhaps save this idea for a few months from now?

**Comment by ggppdk** [comment]
At some point i did examine this and already know what needs to be done
- router (buld/parse)  (not difficult but risky)
- our form JS updated  (easy)
- our getFilterValues updated (easy)

1 or 2 days to implement but i don't want to worry of breaking SEF urls, 

need to finish
- Support for using Joomla article form instead of FLEXIcontent item form (**this is almost done** of course some features will be missing like muti-category assignments and will be added later)
- Syncing with Joomla tags
- Finish Reviews
- Finish Native endless scroll (without using a 3rd party JS) with **proper DB model changes** to make filtered query only once ...
- Finish Configuration import / export

yes a couple of months from now

**Comment by JoshuaLewis** [comment]
That's a great list! :-D Especially the Joomla article form being refactored. Next month Joomla 3.8 is coming with it's new router, so there might be some potential there in terms of simpler structuring. That reason alone is enough to make it worth waiting a bit until we feel that people are upgraded to Joomla 3.8.

**Comment by micker** [comment]
I think the first step is to check modification for new rooter for j3.8

Le 25 août 2017 à 22:22, à 22:22, Georgios Papadakis <notifications@github.com> a écrit:

**Comment by ggppdk** [comment]
About changing the filtering to become segmented, it is still a valid improvement
- but about removing cc=p

i checked cc=p after filtering form submit and it cannot be removed,
it is needed even for guest users
since it is used to enabled to enable HTTP header

**'Cache-Control:  Private/Public'**

that allows page to be cached by browser, 
- avoiding (as explaued above) page has expired browser message when user click Back or Forward buttons, (also it speeds up navigation when Back / Forward are clicked)

**Comment by jimiero** [comment]
@ggppdk what about maybe placing that cc=p inside a cookie or something, instead?

**Comment by ggppdk** [comment]
**Cookie will require communication with server so that browser will send the cookie value to the server**

thus the above will not work
because we want all URLs without cc=* 
to be 
- neither browser cacheable ('Cache-Control: **Private/Public**') 
- nor proxy cacheable ('Cache-Control: **Public**')

and we want them to be non cacheable because their display will depend on current client being logged or not

If a guest user accesses a URL without cc=**** and we tell browser to cache it,
then after user logins, revisiting the page the user will not see the private content but the public from browsers cache

Similar thing will happen if the private contents are cached by the browser, after loggout the local browser will continue to show the private contents

So 
- URL1 is not cacheable

same url with cc=***
- URL1&cc=** is cacheable AND whenever such a URL is opened then we examine the SESSION cookie locally and if a login / logout was done, you will get a redirection to a cc=APROPRIATE value

**Comment by ggppdk** [comment]
Removed unneed URL variables from
&p=all    (actually remove &p=defaultvalue)
&listall=0 

so now you will only have filtering values in text-search / filtering URLs

**Comment by ggppdk** [comment]
Also added 
- proper rel-canonical for filtering URLs 
- max active filter limit (default is 4 filters) before adding "noindex, follow" to instruct search-engines not to index the text-search / filtering pages
