### ISSUE TITLE
Bug on Frontend language, some language strings cannot be changed

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#78]
i translate language file on Front end  but some text not show thai lang

![1212121](https://cloud.githubusercontent.com/assets/2047778/5138416/334f72c8-7181-11e4-8f02-6ad877fc0699.jpg)

i test change Value 
FLEXI_ADD
Front end and Backend language  

on Front end show Value of  Backend 
![2014-11-21_13-16-00](https://cloud.githubusercontent.com/assets/2047778/5138386/cde8f71a-7180-11e4-8b7f-fdcad6e85768.jpg)

**Comment by ggppdk** [comment]
I have seen that some case that 2 same strings are in 2 language files, 

this is maybe ok, in cases for backend configuration (component and modules),

-- TODO: 
1. remove duplicate from modules, ... and check that backend component language file
... is load when any FC module is editted in backend or frontend


2. But for frontend it is not desired since it causes problem, especially in item form,
---> ! of course there could some cases of a forgotten language override in language manager
but in any case we should move -common-  (e.g. ITEM form related strings) into a 3rd component language file and load it backend, and in frontend item form
