### ISSUE TITLE
About removing tabs in frontend item submission form

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#819]
Hello i new front end submission form we have 2 problems :
- display tab is allway display because fielset title is rendered
- joomla compatibility tab is already rendered too

**Comment by ggppdk** [comment]
about "Compatibility" TAB"
- it is shown because in component configuration of Joomla article manager (backend) the images or the links are enabled for frontend

(in flexisystem plugin select to allow super-admins to access "Joomla articles" management)
then visit Joomla article manager , click options and disable for frontend forn

about "Display" TAB
- will need to check it

**Comment by micker** [comment]
thanks for return
