### ISSUE TITLE
Allow personalization text for "Add value" on fields with multiple values ability?

### ISSUE THREAD

**Issue by jimiero** [FLEXIcontent/flexicontent-cck#843]
@ggppdk can you make this text to be able to custom inside fields settings?

Now it uses this common language key "FLEXI_ADD_TO_BOTTOM"

Attaching an image:

![screen shot 2018-02-25 at 1 56 00 pm](https://user-images.githubusercontent.com/3626762/36641163-d0b6c256-1a33-11e8-8671-33806f762407.png)

"Add value" may not be very user-friendly for people

**Comment by ggppdk** [comment]
Currently, you could use Joomla language override to effect all fields

i see the benefit is of having this customizable per field (inside field's settings)
you could have custom text per field like:
Add color
Add term
Add location

In general something like:
Add fieldname

right ?

Also i agree that 'Add value' is not user-friend

This change is easy and rather little time, because the fields have the exact same code
Done this so that is easy to update them or move the common code to method in a parent field class

Anything else similar to 'Add value' ? i mean some other text that would have benefit of being customizable per field ?

**Comment by jimiero** [comment]
Hi @ggppdk, here are some things it may benefit in user-friendly:

![screen shot 2018-02-25 at 2 54 38 pm](https://user-images.githubusercontent.com/3626762/36641664-379e6868-1a3c-11e8-8ebb-f549da11c4ab.png)

For international address field, maybe would be good to have the address type form opened by default?  Currently, I see you need to click "Edit" in order to see the field form, again this may not be friendly for non-developer

**Comment by ggppdk** [comment]
> For international address field, maybe would be good to have the address type form opened by default? 

The above is automatic if field is required,
- i mean make the international address field to be required and it should be open by default

It is closed because when field is not required, there can be some value properties e.g. Country that are required, thus the field would behave as required
that is why it is closed

**Comment by jimiero** [comment]
You're right, sorry my bad

**Comment by ggppdk** [comment]
> You're right, sorry my bad

Implementation of required (value) properties without the value being required was a pain, and had small headache befor finally deciding how to do it

About texts "remove" and "edit"
- you think there is same benefit like the "add value" which indeed should be per field 

1. the remove is only a tooltip, so i think not
2. maybe the "edit", should be customizable per field (for fields that have it)

**Comment by jimiero** [comment]
Agree

**Comment by ggppdk** [comment]
I ll add this to 3.3.x-stable branch,
- probably not to v3.2.1.x-stable later, as there might be a 3.2.1.13 release (currently it is not needed)

**Comment by jimiero** [comment]
@ggppdk sorry, do you know if i did somethng wrong,

In  international address field, I set country / city to store in 2 text fields,

The thing is that I see the country code instead of country name inside the dropdown list

![screen shot 2018-02-25 at 3 31 15 pm](https://user-images.githubusercontent.com/3626762/36641958-f2556e82-1a40-11e8-8ce7-7efb7a171c22.png)

**Comment by ggppdk** [comment]
that is how it works,
the actual value of the every property is stored
and the actual value of the country propery is the countty code

If you want to discuss this further please make a new topic in our forums
