### ISSUE TITLE
Wrong Language when trying to translate

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#852]
My article languages are en-gb.

But I keep seeing en without the -gb and no articles exist.

![GitHub Logo](https://i.imgur.com/rbE1M88.png)

Was this fixed in the last download - 3.2.1.12? Or is it related to the newest Joomla?

**Comment by ggppdk** [comment]
Yes there was a change in Joomla 3.8.5+
that cause the language URL variable to be overwritten in frontend
&language=...

Fix is here, we change the variable name to be '&item_lang='
https://github.com/FLEXIcontent/flexicontent-cck/commit/6e8daa939907dd21641bee327087aed77279e89c

You can use install via URL to get v3.2.1.13-dev
https://github.com/FLEXIcontent/flexicontent-cck/archive/3.2.1.x-stable.zip

Actually there will be v3.2.1.13 because of this and because of a fix in sharemedia and 1 or 2 other smaller issues

**Comment by ggppdk** [comment]
The fix is about selected language associations in frontend
or are you reporting a different issue

**Comment by iamrobert** [comment]
Also I was seeing 3 associations in the box - which confused me - and sometimes I was seeing EN EN - which has never happened before.

I have installed the fix.

**Comment by ggppdk** [comment]
hhmm so you speak of a different issue

about batch translate i think we made a fix recently (? after v3.2.1.12 )
there is an old bug that may cause duplicate associations by batch translate,
i ll check

**Comment by ggppdk** [comment]
The fix i reference above has more benefitss

the popup window in item form to select associations

- will show for every item its existing associations 
- will also prevent selecting an already associated item
- will prevent attempt to save duplicate associations of same language

so it has / should have an effect for batch translate too

**Comment by ggppdk** [comment]
About batch translate,

if you try to translate item NN to a language e.g. fr-FR
but item NN already has an association for language fr-FR

then new item is created without being associated,
we need to skip / abort item creation in such a case

**Comment by iamrobert** [comment]
Thanks for the fix - it seems to be working better.

**Comment by iamrobert** [comment]
Thanks - just want to confirm that multiple translate works. If I select multiple items - it can translate.
