### ISSUE TITLE
Adding theme to select2

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#871]
Adding theme option for select 2
https://github.com/techhysahil/select2-Flat_Theme
https://github.com/select2/select2-bootstrap-theme

**Comment by ggppdk** [comment]
We need to replace select2 JS

since we cannot upgrade to select2 v4.0.x
the reason is that select2 4.0.x is able to perform 5% at the speed of select2 3.x / chosen

this may mean some small part of functionality will be lost
e.g. we now have multiple-select drop-down via checkboxes
that do not submit filtering form until all desired values are selected

**Comment by micker** [comment]
Ok
