### ISSUE TITLE
Lighter CSS for carrousel template

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#902]
I think WE need to refactory CSS code of carrousel template
Remove
 font rules
Color rules
Remove shadow

Maybe add
Color option for background
Color option for description

The goal is to have a better display according template rules

**Comment by micker** [comment]
Maybe WE Can add less option in order to remove inline CSS

**Comment by micker** [comment]
Maybe change title inside captions for a h4

**Comment by micker** [comment]
for all carroussel class have !important ... no sens ...
carroussel have text-shadow, font-family, font-size line height etc .... no sens because need to use template heritage
=> if user want more i can add css
for now to add CSS we need to kill css and after add it .... nightmare for css designer
my team want to kick me ......

**Comment by ggppdk** [comment]
Most (but not all of) !important exist where it is absolutely needed
1. for CSS that are via configuration parameters thus we want them to be enforced !
2. for CSS that shape the carousel so that scrolling width and height does not break ! 

yes we can remove !important for several cases but we cannot do it for all
Please ask team to suggest specific changes that will not break the above 1 and 2 

and we will remove these
you can start testing by removing !important AND ALSO changing the CSS value and check if 1 or 2 break

Also remember all !important rules 
- that are inside CSS files are very easily overridden, just make rule 1 segment longer
- if !important is inside inline styling or inside JS then most likely it should not be touched

**Comment by micker** [comment]
ok i will reply it lol and they can propose something 
first test : we comment 50% of code carroussel.css and remove 90% of important => better adaptation in existing template like helix 
and NO problem of display 
we will inverstigate more

**Comment by micker** [comment]
done
