### ISSUE TITLE
Responsive problem 

### ISSUE THREAD

**Issue by 2CPRESTA** [FLEXIcontent/flexicontent-cck#911]
Hello ! the phone version  of mybwebsite has a small column problem.
Could you help me please ? Thanks

**Comment by ggppdk** [comment]
Please

create a new topic in our forum
as this issue tracker is not for support or anything similar to support

if this is a obvious bug, 
then you may edit your description to provide good details on the bug
and also possible posting a picture about it

Also  you do not mention which view it is, e.g. frontend category view with table ("default") layout ?
- also instead of adding this to the layout only, we will be adding the option
show-when  desktop/tablet/phone in v3.3.0 to all fields

in any case let's better discuss the topic in the forum first

**Comment by 2CPRESTA** [comment]
Ok thanks
