### ISSUE TITLE
textarea not show

### ISSUE THREAD

**Issue by lungkao** [FLEXIcontent/flexicontent-cck#95]
textarea not show on front page version 2.3.0 dev

**Comment by ggppdk** [comment]
Fixed in this commit: 2e52f64

(if you click on the commit please wait several seconds to load, it has too many changes)

Completed new improved item form UI flexicontent fields 

- including revising HTML, CSS, JS for fields in item form for MULTI-value handling

- moved field parameters to have common placement in configuration (updating almost all fields):
 a. Item Form
 b. Frontend (display)
 c. Filtering

- enhanced the intenational phonenumbers field, and other plugins with more configuration options

- made fields: select, radio, radioimage to be ... multi-valued, FOR THE PURPOSE of being used in FIELD GROUPING  (previous commits converted textarea to multi-value)

- completed work on all multi-value fields to support FIELD GROUPING in --item form-- (except for file file, which is not done yet)

NOTE: field group plugin is not on GitHub if you want a copy of it please contact me by email or skype
