### ISSUE TITLE
flexicontent.org SIte Down

### ISSUE THREAD

**Issue by iamrobert** [FLEXIcontent/flexicontent-cck#954]
The https://flexicontent.org/ site has been down for hours. 

https://downforeveryoneorjustme.com/flexicontent.org

When will be back up?

**Comment by ggppdk** [comment]
On every reboot
both the old and new web server services were started

due to some CPANEL script
- the old web server service was being re-enabled every time

and then had to manually stop the old web server service and start the new one

i have fixed the patched the old service to point to new service to avoid the issue, so that this does not happen again when server is rebooted
