### ISSUE TITLE
Colum are set hidden after fresh install

### ISSUE THREAD

**Issue by micker** [FLEXIcontent/flexicontent-cck#995]
hello in fresh install 3.3.8 all columns are hidden in items and category list
![image](https://user-images.githubusercontent.com/2539440/95783395-061a8980-0cd2-11eb-8904-e776a6ea0b0e.png)

**Comment by ggppdk** [comment]
I tested just now
and i cannot confirm this issue

This would happen only if a column cookie is set
i am not sure if installing in a sub-folder on same server would result in initially hidden columns
or with some other chain of steps could result in this ,

i have seen this before but it was because of invalid cookie during my testing

**Comment by ggppdk** [comment]
This may happen if you install master / 3.4 and the install v3.3.8,
cookie format will not be compatible and it will be interpreted as zero columns
